# Build Stage
FROM rust:latest as build
LABEL maintainer="Oscar Sharpe <oscar.sharpe@warwick.ac.uk>"
LABEL version="0.1.0"

WORKDIR /code

COPY . .
RUN cargo build --release

# Image Stage
FROM debian:bullseye as app
LABEL maintainer="Oscar Sharpe <oscar.sharpe@warwick.ac.uk>"
LABEL version="0.1.0"

RUN apt update \
    && apt install curl -y

ENV ROCKET_ENV=production \
    ROCKET_ADDRESS=0.0.0.0 ROCKET_PORT=8080 \
    ROCKET_LOG=critical

EXPOSE 8080

COPY --from=build /code/target/release/rust-notebook /usr/local/bin/rust-notebook
CMD rust-notebook
