version: "3.7"
services:
  js:
    container_name: js-notes
    image: ghcr.io/osharpey/js-notes:latest
    restart: always
    ports:
      - 80:8080
    volumes:
      - /tmp/notes.db:/app/notes.db
