version: "3.7"
services:
  go:
    container_name: go-notes
    image: ghcr.io/osharpey/go-notes:latest
    restart: always
    ports:
      - 80:8080
    volumes:
      - /tmp/notes.db:/app/notes.db
