FROM golang:alpine as builder

LABEL Author="Tom Steer - u2232261"

ENV CGO_ENABLED=1
RUN apk add --no-cache gcc libc-dev
COPY app /app
WORKDIR /app
RUN go build -o main .

FROM alpine:latest

WORKDIR /app
COPY --from=builder /app/main .

EXPOSE 8080

CMD ["/app/main"]
