name: Deploy GO Docker Container
run-name: Go Deploy
on: 
  push:
    branches:
      - main
    paths:
      - "go-notebook/**"


jobs:
  build-and-push-go:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: build-and-push-image
        uses: docker/build-push-action@v4
        with:
          context: go-notebook
          push: true
          tags: "${{ secrets.DOCKER_USER }}/go-notes" 
