name: Deploy Rust Docker Container
run-name: Rust Deploy
on: 
  push:
    branches:
      - main
    paths:
      - "rust-notebook/**"

jobs:      
  build-and-push-rust:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: build-and-push-image
        uses: docker/build-push-action@v4
        with:
          context: rust-notebook
          push: true
          tags: "${{ secrets.DOCKER_USER }}/rust-notes:latest" 
