name: Deploy Terraform to AWS
run-name: Terraform Deploy
on: push

jobs:
  destroy-previous:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run script 
        working-directory: ./destroy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          ./destroy.sh
  deploy-to-aws:
    runs-on: ubuntu-latest
    needs: destroy-previous
    steps:
      - uses: actions/checkout@v3
      - name: Run script
        working-directory: ./terraform
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          terraform init
          terraform plan
          terraform apply -auto-approve

