name: Test Rust Implementation
run-name: Rust Test
on: 
  push:
    paths:
      - "rust-notebook/**"

env:
  REGISTRY: ghcr.io

jobs:
  format-rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Format Rust code
        run: |
          cd rust-notebook/
          cargo fmt --all -- --check 
    
  test-rust:
    runs-on: ubuntu-latest
    needs: format-rust
    steps:
      - uses: actions/checkout@v3
      - name: Ensures package builds
        run: |
          cd rust-notebook/
          cargo test --release
          

