name: Test Go Implementation
run-name: Go Test
on: 
  push:
    paths:
      - "go-notebook/**"

env:
  REGISTRY: ghcr.io

jobs:
  test-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Ensures package builds
        run: |
          cd go-notebook/app
          go build -o main .

